//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: sss_token
// ----------------------------------------------------------------------------
pub mod sss_token {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for sss_token
    pub fn program_id() -> Pubkey {
        pubkey!("GZpZyBHsMrLNmvc6W8ic9SEaZ21BeTfQhW7vKnQPmQiM")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AddMinter
    // ....................................................................

    /// Main instruction struct for AddMinter
    pub struct AddMinterInstruction {
        pub accounts: AddMinterInstructionAccountMetas,
        pub data: AddMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddMinterInstructionAccountMetas {
        pub config: AccountMeta,

        pub minter_info: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddMinter instruction
    #[derive(Debug, Clone)]
    pub struct AddMinterInstructionAccounts {
        pub config: Pubkey,

        pub minter_info: Pubkey,

        pub authority: Pubkey,
    }

    impl AddMinterInstructionAccounts {
        pub fn new(config: Pubkey, minter_info: Pubkey, authority: Pubkey) -> Self {
            Self {
                config,

                minter_info,

                authority,
            }
        }
    }

    /// Instruction data for AddMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddMinterInstructionData {
        pub minter: Pubkey,

        pub quota: u64,
    }

    impl AddMinterInstructionData {
        pub fn new(minter: Pubkey, quota: u64) -> Self {
            Self { minter, quota }
        }
    }

    /// Implementation for AddMinterInstruction
    impl AddMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [75u8, 86u8, 218u8, 40u8, 219u8, 6u8, 141u8, 29u8]
        }

        pub fn data(data: AddMinterInstructionData) -> Self {
            Self {
                accounts: AddMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddMinterInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.minter_info = AccountMeta::new(accounts.minter_info, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: AddRole
    // ....................................................................

    /// Main instruction struct for AddRole
    pub struct AddRoleInstruction {
        pub accounts: AddRoleInstructionAccountMetas,
        pub data: AddRoleInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddRole instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddRoleInstructionAccountMetas {
        pub config: AccountMeta,

        pub role_member: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddRole instruction
    #[derive(Debug, Clone)]
    pub struct AddRoleInstructionAccounts {
        pub config: Pubkey,

        pub role_member: Pubkey,

        pub authority: Pubkey,
    }

    impl AddRoleInstructionAccounts {
        pub fn new(config: Pubkey, role_member: Pubkey, authority: Pubkey) -> Self {
            Self {
                config,

                role_member,

                authority,
            }
        }
    }

    /// Instruction data for AddRole
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddRoleInstructionData {
        pub role: u8,

        pub member: Pubkey,
    }

    impl AddRoleInstructionData {
        pub fn new(role: u8, member: Pubkey) -> Self {
            Self { role, member }
        }
    }

    /// Implementation for AddRoleInstruction
    impl AddRoleInstruction {
        fn discriminator() -> [u8; 8] {
            [45u8, 20u8, 52u8, 132u8, 56u8, 24u8, 179u8, 37u8]
        }

        pub fn data(data: AddRoleInstructionData) -> Self {
            Self {
                accounts: AddRoleInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddRoleInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_member = AccountMeta::new(accounts.role_member, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_member.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: AddToBlacklist
    // ....................................................................

    /// Main instruction struct for AddToBlacklist
    pub struct AddToBlacklistInstruction {
        pub accounts: AddToBlacklistInstructionAccountMetas,
        pub data: AddToBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddToBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddToBlacklistInstructionAccountMetas {
        pub config: AccountMeta,

        pub role_member: AccountMeta,

        pub blacklister: AccountMeta,

        pub blacklist_entry: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddToBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct AddToBlacklistInstructionAccounts {
        pub config: Pubkey,

        pub role_member: Pubkey,

        pub blacklister: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl AddToBlacklistInstructionAccounts {
        pub fn new(
            config: Pubkey,

            role_member: Pubkey,

            blacklister: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                config,

                role_member,

                blacklister,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for AddToBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddToBlacklistInstructionData {
        pub address: Pubkey,

        pub reason: String,
    }

    impl AddToBlacklistInstructionData {
        pub fn new(address: Pubkey, reason: String) -> Self {
            Self { address, reason }
        }
    }

    /// Implementation for AddToBlacklistInstruction
    impl AddToBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [90u8, 115u8, 98u8, 231u8, 173u8, 119u8, 117u8, 176u8]
        }

        pub fn data(data: AddToBlacklistInstructionData) -> Self {
            Self {
                accounts: AddToBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddToBlacklistInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_member = AccountMeta::new_readonly(accounts.role_member, false);

            self.accounts.blacklister = AccountMeta::new(accounts.blacklister, true);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_member.clone());

            metas.push(self.accounts.blacklister.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Burn
    // ....................................................................

    /// Main instruction struct for Burn
    pub struct BurnInstruction {
        pub accounts: BurnInstructionAccountMetas,
        pub data: BurnInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Burn instruction
    #[derive(Debug, Clone, Default)]
    pub struct BurnInstructionAccountMetas {
        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub role_member: AccountMeta,

        pub burner: AccountMeta,

        pub token_account: AccountMeta,

        pub token_2022_program: AccountMeta,
    }

    /// Account pubkeys for Burn instruction
    #[derive(Debug, Clone)]
    pub struct BurnInstructionAccounts {
        pub config: Pubkey,

        pub mint: Pubkey,

        pub role_member: Pubkey,

        pub burner: Pubkey,

        pub token_account: Pubkey,
    }

    impl BurnInstructionAccounts {
        pub fn new(
            config: Pubkey,

            mint: Pubkey,

            role_member: Pubkey,

            burner: Pubkey,

            token_account: Pubkey,
        ) -> Self {
            Self {
                config,

                mint,

                role_member,

                burner,

                token_account,
            }
        }
    }

    /// Instruction data for Burn
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BurnInstructionData {
        pub amount: u64,
    }

    impl BurnInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for BurnInstruction
    impl BurnInstruction {
        fn discriminator() -> [u8; 8] {
            [116u8, 110u8, 29u8, 56u8, 107u8, 219u8, 42u8, 93u8]
        }

        pub fn data(data: BurnInstructionData) -> Self {
            Self {
                accounts: BurnInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BurnInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.role_member = AccountMeta::new_readonly(accounts.role_member, false);

            self.accounts.burner = AccountMeta::new_readonly(accounts.burner, true);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_2022_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.role_member.clone());

            metas.push(self.accounts.burner.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_2022_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FreezeAccount
    // ....................................................................

    /// Main instruction struct for FreezeAccount
    pub struct FreezeAccountInstruction {
        pub accounts: FreezeAccountInstructionAccountMetas,
        pub data: FreezeAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FreezeAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct FreezeAccountInstructionAccountMetas {
        pub config: AccountMeta,

        pub role_member: AccountMeta,

        pub freezer: AccountMeta,

        pub token_account: AccountMeta,

        pub mint: AccountMeta,

        pub token_2022_program: AccountMeta,
    }

    /// Account pubkeys for FreezeAccount instruction
    #[derive(Debug, Clone)]
    pub struct FreezeAccountInstructionAccounts {
        pub config: Pubkey,

        pub role_member: Pubkey,

        pub freezer: Pubkey,

        pub token_account: Pubkey,

        pub mint: Pubkey,
    }

    impl FreezeAccountInstructionAccounts {
        pub fn new(
            config: Pubkey,

            role_member: Pubkey,

            freezer: Pubkey,

            token_account: Pubkey,

            mint: Pubkey,
        ) -> Self {
            Self {
                config,

                role_member,

                freezer,

                token_account,

                mint,
            }
        }
    }

    /// Instruction data for FreezeAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FreezeAccountInstructionData {}

    impl FreezeAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for FreezeAccountInstruction
    impl FreezeAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [253u8, 75u8, 82u8, 133u8, 167u8, 238u8, 43u8, 130u8]
        }

        pub fn data(data: FreezeAccountInstructionData) -> Self {
            Self {
                accounts: FreezeAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FreezeAccountInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_member = AccountMeta::new_readonly(accounts.role_member, false);

            self.accounts.freezer = AccountMeta::new_readonly(accounts.freezer, true);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_2022_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_member.clone());

            metas.push(self.accounts.freezer.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_2022_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub transfer_hook_program: AccountMeta,

        pub transfer_hook_extra_account_metas: AccountMeta,

        pub token_2022_program: AccountMeta,

        pub system_program: AccountMeta,

        pub rent: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub transfer_hook_program: Pubkey,

        pub transfer_hook_extra_account_metas: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            transfer_hook_program: Pubkey,

            transfer_hook_extra_account_metas: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                mint,

                transfer_hook_program,

                transfer_hook_extra_account_metas,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub name: String,

        pub symbol: String,

        pub uri: String,

        pub decimals: u8,

        pub enable_permanent_delegate: bool,

        pub enable_transfer_hook: bool,

        pub default_account_frozen: bool,
    }

    impl InitializeInstructionData {
        pub fn new(
            name: String,

            symbol: String,

            uri: String,

            decimals: u8,

            enable_permanent_delegate: bool,

            enable_transfer_hook: bool,

            default_account_frozen: bool,
        ) -> Self {
            Self {
                name,

                symbol,

                uri,

                decimals,

                enable_permanent_delegate,

                enable_transfer_hook,

                default_account_frozen,
            }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.transfer_hook_program =
                AccountMeta::new_readonly(accounts.transfer_hook_program, false);

            self.accounts.transfer_hook_extra_account_metas =
                AccountMeta::new(accounts.transfer_hook_extra_account_metas, false);

            self.accounts.token_2022_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.rent = AccountMeta::new_readonly(
                pubkey!("SysvarRent111111111111111111111111111111111"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.transfer_hook_program.clone());

            metas.push(self.accounts.transfer_hook_extra_account_metas.clone());

            metas.push(self.accounts.token_2022_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.rent.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Mint
    // ....................................................................

    /// Main instruction struct for Mint
    pub struct MintInstruction {
        pub accounts: MintInstructionAccountMetas,
        pub data: MintInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Mint instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintInstructionAccountMetas {
        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub minter_info: AccountMeta,

        pub minter: AccountMeta,

        pub recipient_token_account: AccountMeta,

        pub token_2022_program: AccountMeta,
    }

    /// Account pubkeys for Mint instruction
    #[derive(Debug, Clone)]
    pub struct MintInstructionAccounts {
        pub config: Pubkey,

        pub mint: Pubkey,

        pub minter_info: Pubkey,

        pub minter: Pubkey,

        pub recipient_token_account: Pubkey,
    }

    impl MintInstructionAccounts {
        pub fn new(
            config: Pubkey,

            mint: Pubkey,

            minter_info: Pubkey,

            minter: Pubkey,

            recipient_token_account: Pubkey,
        ) -> Self {
            Self {
                config,

                mint,

                minter_info,

                minter,

                recipient_token_account,
            }
        }
    }

    /// Instruction data for Mint
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintInstructionData {
        pub amount: u64,
    }

    impl MintInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintInstruction
    impl MintInstruction {
        fn discriminator() -> [u8; 8] {
            [51u8, 57u8, 225u8, 47u8, 182u8, 146u8, 137u8, 166u8]
        }

        pub fn data(data: MintInstructionData) -> Self {
            Self {
                accounts: MintInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.minter_info = AccountMeta::new(accounts.minter_info, false);

            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, true);

            self.accounts.recipient_token_account =
                AccountMeta::new(accounts.recipient_token_account, false);

            self.accounts.token_2022_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.recipient_token_account.clone());

            metas.push(self.accounts.token_2022_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pause
    // ....................................................................

    /// Main instruction struct for Pause
    pub struct PauseInstruction {
        pub accounts: PauseInstructionAccountMetas,
        pub data: PauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pause instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseInstructionAccountMetas {
        pub config: AccountMeta,

        pub role_member: AccountMeta,

        pub pauser: AccountMeta,
    }

    /// Account pubkeys for Pause instruction
    #[derive(Debug, Clone)]
    pub struct PauseInstructionAccounts {
        pub config: Pubkey,

        pub role_member: Pubkey,

        pub pauser: Pubkey,
    }

    impl PauseInstructionAccounts {
        pub fn new(config: Pubkey, role_member: Pubkey, pauser: Pubkey) -> Self {
            Self {
                config,

                role_member,

                pauser,
            }
        }
    }

    /// Instruction data for Pause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseInstructionData {}

    impl PauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseInstruction
    impl PauseInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 22u8, 221u8, 251u8, 74u8, 121u8, 193u8, 47u8]
        }

        pub fn data(data: PauseInstructionData) -> Self {
            Self {
                accounts: PauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_member = AccountMeta::new_readonly(accounts.role_member, false);

            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_member.clone());

            metas.push(self.accounts.pauser.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveFromBlacklist
    // ....................................................................

    /// Main instruction struct for RemoveFromBlacklist
    pub struct RemoveFromBlacklistInstruction {
        pub accounts: RemoveFromBlacklistInstructionAccountMetas,
        pub data: RemoveFromBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveFromBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveFromBlacklistInstructionAccountMetas {
        pub config: AccountMeta,

        pub role_member: AccountMeta,

        pub blacklister: AccountMeta,

        pub blacklist_entry: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for RemoveFromBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct RemoveFromBlacklistInstructionAccounts {
        pub config: Pubkey,

        pub role_member: Pubkey,

        pub blacklister: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl RemoveFromBlacklistInstructionAccounts {
        pub fn new(
            config: Pubkey,

            role_member: Pubkey,

            blacklister: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                config,

                role_member,

                blacklister,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for RemoveFromBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveFromBlacklistInstructionData {
        pub address: Pubkey,
    }

    impl RemoveFromBlacklistInstructionData {
        pub fn new(address: Pubkey) -> Self {
            Self { address }
        }
    }

    /// Implementation for RemoveFromBlacklistInstruction
    impl RemoveFromBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [47u8, 105u8, 20u8, 10u8, 165u8, 168u8, 203u8, 219u8]
        }

        pub fn data(data: RemoveFromBlacklistInstructionData) -> Self {
            Self {
                accounts: RemoveFromBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveFromBlacklistInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_member = AccountMeta::new_readonly(accounts.role_member, false);

            self.accounts.blacklister = AccountMeta::new(accounts.blacklister, true);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_member.clone());

            metas.push(self.accounts.blacklister.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveMinter
    // ....................................................................

    /// Main instruction struct for RemoveMinter
    pub struct RemoveMinterInstruction {
        pub accounts: RemoveMinterInstructionAccountMetas,
        pub data: RemoveMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveMinterInstructionAccountMetas {
        pub config: AccountMeta,

        pub minter_info: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for RemoveMinter instruction
    #[derive(Debug, Clone)]
    pub struct RemoveMinterInstructionAccounts {
        pub config: Pubkey,

        pub minter_info: Pubkey,

        pub authority: Pubkey,
    }

    impl RemoveMinterInstructionAccounts {
        pub fn new(config: Pubkey, minter_info: Pubkey, authority: Pubkey) -> Self {
            Self {
                config,

                minter_info,

                authority,
            }
        }
    }

    /// Instruction data for RemoveMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveMinterInstructionData {
        pub minter: Pubkey,
    }

    impl RemoveMinterInstructionData {
        pub fn new(minter: Pubkey) -> Self {
            Self { minter }
        }
    }

    /// Implementation for RemoveMinterInstruction
    impl RemoveMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [241u8, 69u8, 84u8, 16u8, 164u8, 232u8, 131u8, 79u8]
        }

        pub fn data(data: RemoveMinterInstructionData) -> Self {
            Self {
                accounts: RemoveMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveMinterInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.minter_info = AccountMeta::new(accounts.minter_info, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveRole
    // ....................................................................

    /// Main instruction struct for RemoveRole
    pub struct RemoveRoleInstruction {
        pub accounts: RemoveRoleInstructionAccountMetas,
        pub data: RemoveRoleInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveRole instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveRoleInstructionAccountMetas {
        pub config: AccountMeta,

        pub role_member: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for RemoveRole instruction
    #[derive(Debug, Clone)]
    pub struct RemoveRoleInstructionAccounts {
        pub config: Pubkey,

        pub role_member: Pubkey,

        pub authority: Pubkey,
    }

    impl RemoveRoleInstructionAccounts {
        pub fn new(config: Pubkey, role_member: Pubkey, authority: Pubkey) -> Self {
            Self {
                config,

                role_member,

                authority,
            }
        }
    }

    /// Instruction data for RemoveRole
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveRoleInstructionData {
        pub role: u8,

        pub member: Pubkey,
    }

    impl RemoveRoleInstructionData {
        pub fn new(role: u8, member: Pubkey) -> Self {
            Self { role, member }
        }
    }

    /// Implementation for RemoveRoleInstruction
    impl RemoveRoleInstruction {
        fn discriminator() -> [u8; 8] {
            [74u8, 69u8, 168u8, 163u8, 248u8, 3u8, 130u8, 0u8]
        }

        pub fn data(data: RemoveRoleInstructionData) -> Self {
            Self {
                accounts: RemoveRoleInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveRoleInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_member = AccountMeta::new(accounts.role_member, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_member.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Seize
    // ....................................................................

    /// Main instruction struct for Seize
    pub struct SeizeInstruction {
        pub accounts: SeizeInstructionAccountMetas,
        pub data: SeizeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Seize instruction
    #[derive(Debug, Clone, Default)]
    pub struct SeizeInstructionAccountMetas {
        pub config: AccountMeta,

        pub role_member: AccountMeta,

        pub seizer: AccountMeta,

        pub from_account: AccountMeta,

        pub to_account: AccountMeta,

        pub mint: AccountMeta,

        pub sss_token_program: AccountMeta,

        pub token_2022_program: AccountMeta,
    }

    /// Account pubkeys for Seize instruction
    #[derive(Debug, Clone)]
    pub struct SeizeInstructionAccounts {
        pub config: Pubkey,

        pub role_member: Pubkey,

        pub seizer: Pubkey,

        pub from_account: Pubkey,

        pub to_account: Pubkey,

        pub mint: Pubkey,
    }

    impl SeizeInstructionAccounts {
        pub fn new(
            config: Pubkey,

            role_member: Pubkey,

            seizer: Pubkey,

            from_account: Pubkey,

            to_account: Pubkey,

            mint: Pubkey,
        ) -> Self {
            Self {
                config,

                role_member,

                seizer,

                from_account,

                to_account,

                mint,
            }
        }
    }

    /// Instruction data for Seize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SeizeInstructionData {
        pub amount: u64,
    }

    impl SeizeInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for SeizeInstruction
    impl SeizeInstruction {
        fn discriminator() -> [u8; 8] {
            [129u8, 159u8, 143u8, 31u8, 161u8, 224u8, 241u8, 84u8]
        }

        pub fn data(data: SeizeInstructionData) -> Self {
            Self {
                accounts: SeizeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SeizeInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_member = AccountMeta::new_readonly(accounts.role_member, false);

            self.accounts.seizer = AccountMeta::new_readonly(accounts.seizer, true);

            self.accounts.from_account = AccountMeta::new(accounts.from_account, false);

            self.accounts.to_account = AccountMeta::new(accounts.to_account, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.sss_token_program = AccountMeta::new_readonly(
                pubkey!("GZpZyBHsMrLNmvc6W8ic9SEaZ21BeTfQhW7vKnQPmQiM"),
                false,
            );

            self.accounts.token_2022_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_member.clone());

            metas.push(self.accounts.seizer.clone());

            metas.push(self.accounts.from_account.clone());

            metas.push(self.accounts.to_account.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.sss_token_program.clone());

            metas.push(self.accounts.token_2022_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ThawAccount
    // ....................................................................

    /// Main instruction struct for ThawAccount
    pub struct ThawAccountInstruction {
        pub accounts: ThawAccountInstructionAccountMetas,
        pub data: ThawAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ThawAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct ThawAccountInstructionAccountMetas {
        pub config: AccountMeta,

        pub role_member: AccountMeta,

        pub freezer: AccountMeta,

        pub token_account: AccountMeta,

        pub mint: AccountMeta,

        pub token_2022_program: AccountMeta,
    }

    /// Account pubkeys for ThawAccount instruction
    #[derive(Debug, Clone)]
    pub struct ThawAccountInstructionAccounts {
        pub config: Pubkey,

        pub role_member: Pubkey,

        pub freezer: Pubkey,

        pub token_account: Pubkey,

        pub mint: Pubkey,
    }

    impl ThawAccountInstructionAccounts {
        pub fn new(
            config: Pubkey,

            role_member: Pubkey,

            freezer: Pubkey,

            token_account: Pubkey,

            mint: Pubkey,
        ) -> Self {
            Self {
                config,

                role_member,

                freezer,

                token_account,

                mint,
            }
        }
    }

    /// Instruction data for ThawAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ThawAccountInstructionData {}

    impl ThawAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ThawAccountInstruction
    impl ThawAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [115u8, 152u8, 79u8, 213u8, 213u8, 169u8, 184u8, 35u8]
        }

        pub fn data(data: ThawAccountInstructionData) -> Self {
            Self {
                accounts: ThawAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ThawAccountInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.role_member = AccountMeta::new_readonly(accounts.role_member, false);

            self.accounts.freezer = AccountMeta::new_readonly(accounts.freezer, true);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_2022_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_member.clone());

            metas.push(self.accounts.freezer.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_2022_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferAuthority
    // ....................................................................

    /// Main instruction struct for TransferAuthority
    pub struct TransferAuthorityInstruction {
        pub accounts: TransferAuthorityInstructionAccountMetas,
        pub data: TransferAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferAuthorityInstructionAccountMetas {
        pub config: AccountMeta,

        pub authority: AccountMeta,
    }

    /// Account pubkeys for TransferAuthority instruction
    #[derive(Debug, Clone)]
    pub struct TransferAuthorityInstructionAccounts {
        pub config: Pubkey,

        pub authority: Pubkey,
    }

    impl TransferAuthorityInstructionAccounts {
        pub fn new(config: Pubkey, authority: Pubkey) -> Self {
            Self { config, authority }
        }
    }

    /// Instruction data for TransferAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferAuthorityInstructionData {
        pub new_authority: Pubkey,
    }

    impl TransferAuthorityInstructionData {
        pub fn new(new_authority: Pubkey) -> Self {
            Self { new_authority }
        }
    }

    /// Implementation for TransferAuthorityInstruction
    impl TransferAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [48u8, 169u8, 76u8, 72u8, 229u8, 180u8, 55u8, 161u8]
        }

        pub fn data(data: TransferAuthorityInstructionData) -> Self {
            Self {
                accounts: TransferAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferAuthorityInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Unpause
    // ....................................................................

    /// Main instruction struct for Unpause
    pub struct UnpauseInstruction {
        pub accounts: UnpauseInstructionAccountMetas,
        pub data: UnpauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Unpause instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpauseInstructionAccountMetas {
        pub config: AccountMeta,

        pub role_member: AccountMeta,

        pub pauser: AccountMeta,
    }

    /// Account pubkeys for Unpause instruction
    #[derive(Debug, Clone)]
    pub struct UnpauseInstructionAccounts {
        pub config: Pubkey,

        pub role_member: Pubkey,

        pub pauser: Pubkey,
    }

    impl UnpauseInstructionAccounts {
        pub fn new(config: Pubkey, role_member: Pubkey, pauser: Pubkey) -> Self {
            Self {
                config,

                role_member,

                pauser,
            }
        }
    }

    /// Instruction data for Unpause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpauseInstructionData {}

    impl UnpauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpauseInstruction
    impl UnpauseInstruction {
        fn discriminator() -> [u8; 8] {
            [169u8, 144u8, 4u8, 38u8, 10u8, 141u8, 188u8, 255u8]
        }

        pub fn data(data: UnpauseInstructionData) -> Self {
            Self {
                accounts: UnpauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpauseInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.role_member = AccountMeta::new_readonly(accounts.role_member, false);

            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.role_member.clone());

            metas.push(self.accounts.pauser.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateMinterQuota
    // ....................................................................

    /// Main instruction struct for UpdateMinterQuota
    pub struct UpdateMinterQuotaInstruction {
        pub accounts: UpdateMinterQuotaInstructionAccountMetas,
        pub data: UpdateMinterQuotaInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateMinterQuota instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateMinterQuotaInstructionAccountMetas {
        pub config: AccountMeta,

        pub minter_info: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for UpdateMinterQuota instruction
    #[derive(Debug, Clone)]
    pub struct UpdateMinterQuotaInstructionAccounts {
        pub config: Pubkey,

        pub minter_info: Pubkey,

        pub authority: Pubkey,
    }

    impl UpdateMinterQuotaInstructionAccounts {
        pub fn new(config: Pubkey, minter_info: Pubkey, authority: Pubkey) -> Self {
            Self {
                config,

                minter_info,

                authority,
            }
        }
    }

    /// Instruction data for UpdateMinterQuota
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateMinterQuotaInstructionData {
        pub minter: Pubkey,

        pub new_quota: u64,
    }

    impl UpdateMinterQuotaInstructionData {
        pub fn new(minter: Pubkey, new_quota: u64) -> Self {
            Self { minter, new_quota }
        }
    }

    /// Implementation for UpdateMinterQuotaInstruction
    impl UpdateMinterQuotaInstruction {
        fn discriminator() -> [u8; 8] {
            [221u8, 28u8, 229u8, 118u8, 214u8, 28u8, 220u8, 247u8]
        }

        pub fn data(data: UpdateMinterQuotaInstructionData) -> Self {
            Self {
                accounts: UpdateMinterQuotaInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateMinterQuotaInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.minter_info = AccountMeta::new(accounts.minter_info, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_info.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: AccountFrozen
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AccountFrozen {
    pub config: Pubkey,

    pub freezer: Pubkey,

    pub account: Pubkey,
}

impl AccountFrozen {
    pub fn new(config: Pubkey, freezer: Pubkey, account: Pubkey) -> Self {
        Self {
            config,

            freezer,

            account,
        }
    }
}

/// Custom struct: AccountThawed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AccountThawed {
    pub config: Pubkey,

    pub freezer: Pubkey,

    pub account: Pubkey,
}

impl AccountThawed {
    pub fn new(config: Pubkey, freezer: Pubkey, account: Pubkey) -> Self {
        Self {
            config,

            freezer,

            account,
        }
    }
}

/// Custom struct: AddedToBlacklist
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AddedToBlacklist {
    pub config: Pubkey,

    pub blacklister: Pubkey,

    pub address: Pubkey,

    pub reason: String,
}

impl AddedToBlacklist {
    pub fn new(config: Pubkey, blacklister: Pubkey, address: Pubkey, reason: String) -> Self {
        Self {
            config,

            blacklister,

            address,

            reason,
        }
    }
}

/// Custom struct: AuthorityTransferred
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AuthorityTransferred {
    pub config: Pubkey,

    pub old_authority: Pubkey,

    pub new_authority: Pubkey,
}

impl AuthorityTransferred {
    pub fn new(config: Pubkey, old_authority: Pubkey, new_authority: Pubkey) -> Self {
        Self {
            config,

            old_authority,

            new_authority,
        }
    }
}

/// Custom struct: BlacklistEntry
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistEntry {
    pub config: Pubkey,

    pub address: Pubkey,

    pub reason: String,

    pub timestamp: i64,

    pub bump: u8,
}

impl BlacklistEntry {
    pub fn new(config: Pubkey, address: Pubkey, reason: String, timestamp: i64, bump: u8) -> Self {
        Self {
            config,

            address,

            reason,

            timestamp,

            bump,
        }
    }
}

/// Custom struct: Burned
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Burned {
    pub config: Pubkey,

    pub burner: Pubkey,

    pub amount: u64,
}

impl Burned {
    pub fn new(config: Pubkey, burner: Pubkey, amount: u64) -> Self {
        Self {
            config,

            burner,

            amount,
        }
    }
}

/// Custom struct: Minted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Minted {
    pub config: Pubkey,

    pub minter: Pubkey,

    pub recipient: Pubkey,

    pub amount: u64,
}

impl Minted {
    pub fn new(config: Pubkey, minter: Pubkey, recipient: Pubkey, amount: u64) -> Self {
        Self {
            config,

            minter,

            recipient,

            amount,
        }
    }
}

/// Custom struct: MinterAdded
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterAdded {
    pub config: Pubkey,

    pub minter: Pubkey,

    pub quota: u64,
}

impl MinterAdded {
    pub fn new(config: Pubkey, minter: Pubkey, quota: u64) -> Self {
        Self {
            config,

            minter,

            quota,
        }
    }
}

/// Custom struct: MinterInfo
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterInfo {
    pub config: Pubkey,

    pub minter: Pubkey,

    pub quota: u64,

    pub minted: u64,

    pub bump: u8,
}

impl MinterInfo {
    pub fn new(config: Pubkey, minter: Pubkey, quota: u64, minted: u64, bump: u8) -> Self {
        Self {
            config,

            minter,

            quota,

            minted,

            bump,
        }
    }
}

/// Custom struct: MinterQuotaUpdated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterQuotaUpdated {
    pub config: Pubkey,

    pub minter: Pubkey,

    pub old_quota: u64,

    pub new_quota: u64,
}

impl MinterQuotaUpdated {
    pub fn new(config: Pubkey, minter: Pubkey, old_quota: u64, new_quota: u64) -> Self {
        Self {
            config,

            minter,

            old_quota,

            new_quota,
        }
    }
}

/// Custom struct: MinterRemoved
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterRemoved {
    pub config: Pubkey,

    pub minter: Pubkey,
}

impl MinterRemoved {
    pub fn new(config: Pubkey, minter: Pubkey) -> Self {
        Self { config, minter }
    }
}

/// Custom struct: RemovedFromBlacklist
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RemovedFromBlacklist {
    pub config: Pubkey,

    pub blacklister: Pubkey,

    pub address: Pubkey,
}

impl RemovedFromBlacklist {
    pub fn new(config: Pubkey, blacklister: Pubkey, address: Pubkey) -> Self {
        Self {
            config,

            blacklister,

            address,
        }
    }
}

/// Custom struct: RoleAdded
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleAdded {
    pub config: Pubkey,

    pub role: u8,

    pub member: Pubkey,
}

impl RoleAdded {
    pub fn new(config: Pubkey, role: u8, member: Pubkey) -> Self {
        Self {
            config,

            role,

            member,
        }
    }
}

/// Custom struct: RoleMember
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleMember {
    pub config: Pubkey,

    pub role: u8,

    pub member: Pubkey,

    pub bump: u8,
}

impl RoleMember {
    pub fn new(config: Pubkey, role: u8, member: Pubkey, bump: u8) -> Self {
        Self {
            config,

            role,

            member,

            bump,
        }
    }
}

/// Custom struct: RoleRemoved
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleRemoved {
    pub config: Pubkey,

    pub role: u8,

    pub member: Pubkey,
}

impl RoleRemoved {
    pub fn new(config: Pubkey, role: u8, member: Pubkey) -> Self {
        Self {
            config,

            role,

            member,
        }
    }
}

/// Custom struct: Seized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Seized {
    pub config: Pubkey,

    pub seizer: Pubkey,

    pub from_account: Pubkey,

    pub to_account: Pubkey,

    pub amount: u64,
}

impl Seized {
    pub fn new(
        config: Pubkey,

        seizer: Pubkey,

        from_account: Pubkey,

        to_account: Pubkey,

        amount: u64,
    ) -> Self {
        Self {
            config,

            seizer,

            from_account,

            to_account,

            amount,
        }
    }
}

/// Custom struct: StablecoinConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinConfig {
    pub authority: Pubkey,

    pub mint: Pubkey,

    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,

    pub bump: u8,

    pub mint_bump: u8,

    pub transfer_hook_program: Option<Pubkey>,

    pub paused: bool,

    pub _reserved: [u8; 64],
}

impl StablecoinConfig {
    pub fn new(
        authority: Pubkey,

        mint: Pubkey,

        name: String,

        symbol: String,

        uri: String,

        decimals: u8,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,

        bump: u8,

        mint_bump: u8,

        transfer_hook_program: Option<Pubkey>,

        paused: bool,

        _reserved: [u8; 64],
    ) -> Self {
        Self {
            authority,

            mint,

            name,

            symbol,

            uri,

            decimals,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,

            bump,

            mint_bump,

            transfer_hook_program,

            paused,

            _reserved,
        }
    }
}

/// Custom struct: StablecoinInitialized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinInitialized {
    pub authority: Pubkey,

    pub mint: Pubkey,

    pub name: String,

    pub symbol: String,

    pub decimals: u8,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,
}

impl StablecoinInitialized {
    pub fn new(
        authority: Pubkey,

        mint: Pubkey,

        name: String,

        symbol: String,

        decimals: u8,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,
    ) -> Self {
        Self {
            authority,

            mint,

            name,

            symbol,

            decimals,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,
        }
    }
}

/// Custom struct: TokenPaused
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokenPaused {
    pub config: Pubkey,

    pub pauser: Pubkey,
}

impl TokenPaused {
    pub fn new(config: Pubkey, pauser: Pubkey) -> Self {
        Self { config, pauser }
    }
}

/// Custom struct: TokenUnpaused
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokenUnpaused {
    pub config: Pubkey,

    pub pauser: Pubkey,
}

impl TokenUnpaused {
    pub fn new(config: Pubkey, pauser: Pubkey) -> Self {
        Self { config, pauser }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
